# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "aggrigorS" do |control|
    control.vm.hostname = "aggrigorS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.name = "aggrigorS"
      v.cpus = 2
      v.memory = 2048
    end
    control.vm.provision "shell", path: "scripts/server_provision.sh"
  end
end
